personagens = {
    1: {
        "nome": "Enigma",
        "classe": "Renegado",
        "força": 7,
        "destreza": 8,
        "inteligência": 9,
        "idade": 32,
        "história": "Enigma é um ex-agente de elite do Grupo Aegis, que agora carrega consigo o último fragmento de um código proibido capaz de reescrever a realidade virtual. Sua busca pela Ascensão o coloca no centro de uma luta pelo poder em Nexus Prime, onde segredos sombrios e traições estão em toda parte. Enigma é um enigma para todos, e seu destino é incerto.",
        "imagem": "../static/img/personagens/enigma.jpg",
    },
    2: {
        "nome": "Vera Voltage",
        "classe": "Engenheira de Energia",
        "força": 6,
        "destreza": 7,
        "inteligência": 9,
        "idade": 30,
        "história": "Vera é uma engenheira talentosa que projeta e mantém fontes de energia em uma cidade cyberpunk sobrecarregada por tecnologia.",
        "imagem": "../static/img/personagens/vera-voltage.jpg",
    },
    3: {
        "nome": "Shadow Striker",
        "classe": "Mercenário das Sombras",
        "força": 8,
        "destreza": 8,
        "inteligência": 7,
        "idade": 35,
        "história": "Shadow é um mercenário misterioso que atua nas sombras, especializado em missões secretas e assassinatos de alvos de alto nível.",
        "imagem": "../static/img/personagens/shadow-striker.jpg",
    },
    4: {
        "nome": "Luna Skye",
        "classe": "Caçadora de Relíquias",
        "força": 7,
        "destreza": 9,
        "inteligência": 7,
        "idade": 28,
        "história": "Luna é uma caçadora de relíquias que explora ruínas tecnológicas em busca de artefatos valiosos e segredos do passado.",
        "imagem": "../static/img/personagens/luna-skye.jpg",
    },
    5: {
        "nome": "Sam Shadow",
        "classe": "Detetive Digital",
        "força": 6,
        "destreza": 8,
        "inteligência": 9,
        "idade": 32,
        "história": "Sam é um detetive digital especializado em resolver crimes cibernéticos e rastrear transações ilegais na rede.",
        "imagem": "../static/img/personagens/sam-shadow.jpg",
    },
    6: {
        "nome": "Aiden Black",
        "classe": "Assassino de Aluguel",
        "força": 9,
        "destreza": 7,
        "inteligência": 6,
        "idade": 30,
        "história": "Aiden é um assassino de aluguel frio e calculista que é contratado para eliminar alvos de alto valor em uma cidade dominada pela corrupção.",
        "imagem": "../static/img/personagens/aiden-black.jpg",
    },
    7: {
        "nome": "Riley Rogue",
        "classe": "Contrabandista de Cibernéticos",
        "força": 7,
        "destreza": 8,
        "inteligência": 8,
        "idade": 27,
        "história": "Riley é um contrabandista de tecnologia cibernética, fornecendo implantes ilegais e modificações para os que buscam vantagens tecnológicas.",
        "imagem": "thumbnail",
    },
    8: {
        "nome": "Zoe Zenith",
        "classe": "Engenheira de Robôs",
        "força": 6,
        "destreza": 7,
        "inteligência": 9,
        "idade": 31,
        "história": "Zoe é uma engenheira especializada em robótica que projeta e repara robôs para diversos fins, de assistentes domésticos a máquinas de combate.",
        "imagem": "thumbnail",
    },
    9: {
        "nome": "Ethan Echo",
        "classe": "Diplomata Cibernético",
        "força": 5,
        "destreza": 7,
        "inteligência": 10,
        "idade": 40,
        "história": "Ethan é um diplomata que utiliza suas habilidades tecnológicas para resolver conflitos internacionais e questões políticas complexas.",
        "imagem": "thumbnail",
    },
    10: {
        "nome": "Nova Nexus",
        "classe": "Explorador de Realidades Virtuais",
        "força": 4,
        "destreza": 6,
        "inteligência": 10,
        "idade": 26,
        "história": "Nova é uma exploradora de mundos virtuais, criando ambientes virtuais surreais e experiências sensoriais únicas para os usuários.",
        "imagem": "thumbnail",
    },
    11: {
        "nome": "Cipher Cog",
        "classe": "Cientista de Cibernética",
        "força": 5,
        "destreza": 7,
        "inteligência": 10,
        "idade": 32,
        "história": "Cipher Cog é um cientista renomado que trabalha na vanguarda da cibernética, explorando o potencial da fusão humano-máquina.",
        "imagem": "thumbnail",
    },
    12: {
        "nome": "Nina Nexus",
        "classe": "Engenheira de Drones",
        "força": 5,
        "destreza": 9,
        "inteligência": 8,
        "idade": 28,
        "história": "Nina é uma especialista em drones, projetando e pilotando essas máquinas para uma variedade de aplicações, desde entregas até vigilância.",
        "imagem": "thumbnail",
    },
    13: {
        "nome": "Zero Zephyr",
        "classe": "Explorador de Ruínas Tecnológicas",
        "força": 7,
        "destreza": 8,
        "inteligência": 8,
        "idade": 34,
        "história": "Zero é um aventureiro que explora ruínas tecnológicas em busca de tecnologia perdida e segredos esquecidos.",
        "imagem": "thumbnail",
    },
    14: {
        "nome": "Mara Matrix",
        "classe": "Hacker Anarquista",
        "força": 5,
        "destreza": 9,
        "inteligência": 9,
        "idade": 25,
        "história": "Mara é uma hacker comprometida com a luta contra o controle do governo e das corporações, utilizando suas habilidades para desafiar o sistema.",
        "imagem": "thumbnail",
    },
    15: {
        "nome": "Neo Neon",
        "classe": "Artista de Realidade Virtual",
        "força": 4,
        "destreza": 6,
        "inteligência": 10,
        "idade": 30,
        "história": "Neo é um artista talentoso que cria mundos virtuais surpreendentes e experiências sensoriais imersivas para quem busca escapar da realidade.",
        "imagem": "thumbnail",
    },
    16: {
        "nome": "Blaze Byte",
        "classe": "Pirata Cibernético",
        "força": 6,
        "destreza": 7,
        "inteligência": 9,
        "idade": 27,
        "história": "Blaze Byte é um pirata cibernético que atua nas sombras, roubando informações valiosas e penetrando em redes corporativas protegidas.",
        "imagem": "thumbnail",
    },
    17: {
        "nome": "Astra Aurora",
        "classe": "Astroengenheira",
        "força": 5,
        "destreza": 8,
        "inteligência": 9,
        "idade": 33,
        "história": "Astra é uma engenheira que projeta naves espaciais avançadas e lidera expedições interplanetárias em busca de novos horizontes.",
        "imagem": "thumbnail",
    },
    18: {
        "nome": "Orion Octane",
        "classe": "Corredor de Rua Cibernética",
        "força": 7,
        "destreza": 10,
        "inteligência": 6,
        "idade": 29,
        "história": "Orion é um corredor de rua cibernética que compete em corridas ilegais e modifica veículos para obter vantagens nas pistas urbanas.",
        "imagem": "thumbnail",
    },
    19: {
        "nome": "Valkyrie Vortex",
        "classe": "Caçadora de Caçadores",
        "força": 8,
        "destreza": 9,
        "inteligência": 7,
        "idade": 31,
        "história": "Valkyrie é uma caçadora de caçadores implacável, especializada em rastrear e capturar fugitivos e caçadores de recompensas.",
        "imagem": "thumbnail",
    },
    20: {
        "nome": "Zig Zag",
        "classe": "Contrabandista de Arte",
        "força": 6,
        "destreza": 7,
        "inteligência": 8,
        "idade": 26,
        "história": "Zig Zag é um contrabandista de arte que trafica obras roubadas e opera no mundo subterrâneo das galerias de arte ilegais.",
        "imagem": "thumbnail",
    },
}

usuarios = {
    1: {
        "nome": "Karla Silva",
        "email": "karlasilvaeng@gmail.com",
        "senha": "grupo3koru",
    }
}
